name: flutter_notes
description: "App for storing your notes."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  collection: ^1.18.0
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  provider: ^6.1.1
  surf_logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^3.0.0

flutter:
  uses-material-design: true
